# ===== eKart Test Configuration =====
base.url=https://ekartms.netlify.app
browser=chrome

valid.email=user@ekart.com
valid.password=User@123
implicit.wait=1
explicit.wait=1
headless=false
reg.email=testuser@example.com
reg.password=Test@1234
reg.phone=9876543210
reg.firstName=Test
reg.lastName=User
login.valid.email=user@ekart.com
login.valid.password=User@123
login.invalid.email=wrong@example.com
login.invalid.password=Wrong@999

# Admin credentials
admin.email=aprs@ekart.com
admin.password=aps134